version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql
#    volumes:
#      - mysql-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'go-clean-template'
    ports:
      - 3306:3306

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'testuser:password@tcp(mysql)/go-clean-template'
    ports:
      - 8080:8080
    depends_on:
      - mysql

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  mysql-data:
